// src/app/layout.js
import { SkiperCardDemo } from "./pages/Skipper";
import { TextScrollDemo } from "./Usage/textsc";

export const metadata = {
  title: "My Website",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
  <>

<SkiperCardDemo></SkiperCardDemo>
<TextScrollDemo></TextScrollDemo>
<div></div>


       
    </>
  );
}
